export class Job {
    constructor(
        public id: number,
        public job_type: object,
        public job_type_rev: object,
        public event: object,
        public error: object,
        public status: string,
        public priority: number,
        public num_exes: number,
        public timeout: number,
        public max_tries: number,
        public cpus_required: number,
        public mem_required: number,
        public disk_in_required: number,
        public disk_out_required: number,
        public is_superseded: boolean,
        public root_superseded_job: object,
        public superseded_job: object,
        public superseded_by_job: object,
        public delete_superseded: boolean,
        public created: Date,
        public queued: Date,
        public started: Date,
        public ended: Date,
        public last_status_change: Date,
        public superseded: Date,
        public last_modified: Date,
        public data: object,
        public results: object,
        public recipes: Array<object>,
        public job_exes: Array<object>,
        public inputs: Array<object>,
        public outputs: Array<object>
    ) {}
}
